<?php 
	session_start();
	$_SESSION['f1']=0;
	$_SESSION['f2']=0;
	$_SESSION['f3']=0;
	$_SESSION['f4']=0;
	$_SESSION['f5']=0;	
	$_SESSION['f6']=0;
	$_SESSION['f7']=0;
	$_SESSION['f8']=0;
	$_SESSION['j1']=0;
	$_SESSION['total']=0;
	header('Location:Dashboard.php');
?>